// File generated by the FlutterFire CLI.
// To generate, run: `flutterfire configure --project=your-firebase-project`
// For more info, see: https://firebase.flutter.dev/docs/cli

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return android; // Use Android config for Windows testing
      case TargetPlatform.linux:
        return android; // Use Android config for Linux testing
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWfsRYAIwLENLhwumOMOJlvOwYItqq4QA',
    appId: '1:344119692090:android:17dbc22dd270318f9e9e03',
    messagingSenderId: '344119692090',
    projectId: 'e-learning-31b22',
    storageBucket: 'e-learning-31b22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWfsRYAIwLENLhwumOMOJlvOwYItqq4QA',
    appId: '1:344119692090:ios:17dbc22dd270318f9e9e03',
    messagingSenderId: '344119692090',
    projectId: 'e-learning-31b22',
    storageBucket: 'e-learning-31b22.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWfsRYAIwLENLhwumOMOJlvOwYItqq4QA',
    appId: '1:344119692090:ios:17dbc22dd270318f9e9e03',
    messagingSenderId: '344119692090',
    projectId: 'e-learning-31b22',
    storageBucket: 'e-learning-31b22.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWfsRYAIwLENLhwumOMOJlvOwYItqq4QA',
    appId: '1:344119692090:web:17dbc22dd270318f9e9e03',
    messagingSenderId: '344119692090',
    projectId: 'e-learning-31b22',
    storageBucket: 'e-learning-31b22.firebasestorage.app',
    authDomain: 'e-learning-31b22.firebaseapp.com',
  );

  }
